wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: huggingface
    huggingface_version: 4.21.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1745731556.692058
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.13.1
      6: 4.21.1
      8:
      - 5
action_emb_dim:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 32
data_dir:
  desc: null
  value: /gpfs/scratch/wz1492/data/train
encoder_name:
  desc: null
  value: dinov2_vits14
epochs:
  desc: null
  value: 50
feature_key:
  desc: null
  value: x_norm_patchtokens
lr:
  desc: null
  value: 0.0001
no_teacher_forcing:
  desc: null
  value: false
num_hist:
  desc: null
  value: 16
num_pred:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 4
output_dir:
  desc: null
  value: runs
predictor_depth:
  desc: null
  value: 4
predictor_dim_head:
  desc: null
  value: 32
predictor_dropout:
  desc: null
  value: 0
predictor_emb_dropout:
  desc: null
  value: 0
predictor_heads:
  desc: null
  value: 4
predictor_mlp_dim:
  desc: null
  value: 512
predictor_pool:
  desc: null
  value: attn
save_path:
  desc: null
  value: jepa_model_small_sam_1_mse.pth
sched_sample_prob:
  desc: null
  value: 1.0
vicreg:
  desc: null
  value: false
